version: '3.1'

services:

  db:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017 # REMOVE this in a production environment!

  app:
    build: .
    ports:
      - ${APP_PORT}:3000
    links:
      - db
    depends_on:
      - db
